### ISSUE TITLE
Keyboard key off event is probably not processed in your program. 

### ISSUE THREAD

**Issue by happymimimix** [Mivik/prpr#11] opened 2023-02-24 12:12 UTC
I didn't turn on auto play. 
But I find all yellow and pink keys get pressed automatically on its own. 
I tested it for some more times and discovered that this won't happen at the very beginning, 
but if you press a key on your keyboard once, then all the remaining yellow and pink keys will be pressed automatically. 
The reason I guessed is probably because you forgot about the key off event in the program. 
All keys you've pressed are never released in the program. 
Please check your code.

**Comment by Mivik** [comment] 2023-02-24 12:14
duplicate of #8

**Closed as completed by Mivik** 2023-02-24 12:14 UTC
